### ISSUE TITLE
Style svg icons via classes 

### ISSUE THREAD

**Issue by howdu** [UtkarshVerma/hugo-modules#1]
Would it be possible to pass extra data into the partial? e.g tailwind utility classes.

`{{ partial "svg" "fas fa-star" "w-12 h-12 fill-blue-500" }}`

**Comment by howdu** [comment]
Also a useful error message if the icon is not found would be helpful too.

**Comment by UtkarshVerma** [comment]
Implemented this through #[60c3bbf](https://github.com/UtkarshVerma/hugo-modules/commit/60c3bbfb0f989325b32975d9a74e482c38589545). Now you should be able to specify any attribute for the SVG. Check the README for examples.
